/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/twilio/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Twilio Whatsapp */
        post: operations["twilio_whatsapp_webhooks_twilio_whatsapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deployment Status */
        get: operations["deployment_status_internal_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_internal_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_internal_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_internal_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/conversations/{conversation_id}/panel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Conversation Panel */
        patch: operations["patch_conversation_panel_internal_conversations__conversation_id__panel_patch"];
        trace?: never;
    };
    "/internal/conversations/{conversation_id}/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Handoff */
        post: operations["create_handoff_internal_conversations__conversation_id__handoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace Settings */
        get: operations["get_workspace_settings_internal_settings_get"];
        /** Put Workspace Settings */
        put: operations["put_workspace_settings_internal_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/settings/agent-catalog/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Agent Catalog Upload
         * @description Convierte CSV o Excel (.xlsx) en líneas «celda | celda | …» para pegar en el catálogo del agente.
         */
        post: operations["parse_agent_catalog_upload_internal_settings_agent_catalog_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Comprueba conexión a Postgres (útil en orquestadores / balanceadores).
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus Metrics
         * @description Prometheus scrape (restringir en red en producción).
         */
        get: operations["prometheus_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_parse_agent_catalog_upload_internal_settings_agent_catalog_parse_post */
        Body_parse_agent_catalog_upload_internal_settings_agent_catalog_parse_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CatalogParseOut */
        CatalogParseOut: {
            /** Catalog Fragment */
            catalog_fragment: string;
            /** Rows Imported */
            rows_imported: number;
            /** File Type */
            file_type: string;
        };
        /** ConversationDetail */
        ConversationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Twilio From */
            twilio_from: string;
            /** Twilio To */
            twilio_to: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
            lead: components["schemas"]["LeadOut"] | null;
            /** Internal Notes */
            internal_notes?: string | null;
            /** Internal Tags */
            internal_tags?: string[];
            /**
             * Last Agent Llm Status
             * @default ok
             */
            last_agent_llm_status: string;
            /** Last Agent Llm Error */
            last_agent_llm_error?: string | null;
            pending_handoff?: components["schemas"]["HandoffBrief"] | null;
        };
        /** ConversationPanelOut */
        ConversationPanelOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Internal Notes */
            internal_notes: string | null;
            /** Internal Tags */
            internal_tags: string[];
        };
        /** ConversationPanelPatch */
        ConversationPanelPatch: {
            /** Internal Notes */
            internal_notes?: string | null;
            /** Internal Tags */
            internal_tags?: string[] | null;
        };
        /** ConversationSummary */
        ConversationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Twilio From */
            twilio_from: string;
            /** Twilio To */
            twilio_to: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Message Count */
            message_count: number;
            /** Last Agent Llm Status */
            last_agent_llm_status: string;
        };
        /** DeploymentStatus */
        DeploymentStatus: {
            /** Api Version */
            api_version: string;
            /** Git Commit */
            git_commit: string;
            /** Database */
            database: string;
            /**
             * Redis Configured
             * @default false
             */
            redis_configured: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandoffBrief */
        HandoffBrief: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HandoffCreate */
        HandoffCreate: {
            /**
             * Reason
             * @default manual_from_dashboard
             */
            reason: string;
        };
        /** HandoffOut */
        HandoffOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LeadListItem */
        LeadListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Twilio From */
            twilio_from: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string | null;
            /** Name */
            name: string | null;
            /** Stage */
            stage: string;
            /** Qualification */
            qualification: {
                [key: string]: unknown;
            } | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LeadOut */
        LeadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string | null;
            /** Name */
            name: string | null;
            /** Stage */
            stage: string;
            /** Qualification */
            qualification: {
                [key: string]: unknown;
            } | null;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Direction */
            direction: string;
            /** Body */
            body: string;
            /** Twilio Message Sid */
            twilio_message_sid: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SettingsPublic */
        SettingsPublic: {
            /** Twilio Account Sid */
            twilio_account_sid: string;
            /** Webhook Base Url */
            webhook_base_url: string;
            /** Twilio Validate Signature */
            twilio_validate_signature: boolean;
            /** Llm Provider */
            llm_provider: string;
            /** Openai Model */
            openai_model: string;
            /** Gemini Model */
            gemini_model: string;
            /** Twilio Auth Token Configured */
            twilio_auth_token_configured: boolean;
            /** Openai Api Key Configured */
            openai_api_key_configured: boolean;
            /** Gemini Api Key Configured */
            gemini_api_key_configured: boolean;
            /** Twilio Webhook Full Url */
            twilio_webhook_full_url: string;
            /** Agent Business Summary */
            agent_business_summary: string;
            /** Agent Instructions */
            agent_instructions: string;
            /** Agent Lead Capture */
            agent_lead_capture: string;
            /** Agent Catalog */
            agent_catalog: string;
            /** Agent Pricing Rules */
            agent_pricing_rules: string;
            /** Agent Shipping Zones */
            agent_shipping_zones: string;
            /** Agent Payment Methods */
            agent_payment_methods: string;
            /** Agent Returns Warranty */
            agent_returns_warranty: string;
            /** Agent Faq */
            agent_faq: string;
            /** Agent Off Hours Message */
            agent_off_hours_message: string;
            /** Agent Hard Rules */
            agent_hard_rules: string;
        };
        /**
         * SettingsUpdate
         * @description Solo se actualizan campos enviados. Cadena vacía en secretos borra el valor guardado en BD (vuelve al .env).
         */
        SettingsUpdate: {
            /** Twilio Account Sid */
            twilio_account_sid?: string | null;
            /** Twilio Auth Token */
            twilio_auth_token?: string | null;
            /** Webhook Base Url */
            webhook_base_url?: string | null;
            /** Twilio Validate Signature */
            twilio_validate_signature?: boolean | null;
            /** Llm Provider */
            llm_provider?: ("openai" | "gemini") | null;
            /** Openai Api Key */
            openai_api_key?: string | null;
            /** Openai Model */
            openai_model?: string | null;
            /** Gemini Api Key */
            gemini_api_key?: string | null;
            /** Gemini Model */
            gemini_model?: string | null;
            /** Agent Business Summary */
            agent_business_summary?: string | null;
            /** Agent Instructions */
            agent_instructions?: string | null;
            /** Agent Lead Capture */
            agent_lead_capture?: string | null;
            /** Agent Catalog */
            agent_catalog?: string | null;
            /** Agent Pricing Rules */
            agent_pricing_rules?: string | null;
            /** Agent Shipping Zones */
            agent_shipping_zones?: string | null;
            /** Agent Payment Methods */
            agent_payment_methods?: string | null;
            /** Agent Returns Warranty */
            agent_returns_warranty?: string | null;
            /** Agent Faq */
            agent_faq?: string | null;
            /** Agent Off Hours Message */
            agent_off_hours_message?: string | null;
            /** Agent Hard Rules */
            agent_hard_rules?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    twilio_whatsapp_webhooks_twilio_whatsapp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    deployment_status_internal_status_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_internal_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Teléfono, canal o texto en lead (nombre/email/tel) */
                q?: string | null;
                /** @description open | handed_off | closed */
                status?: string | null;
                /** @description updated_at >= (YYYY-MM-DD UTC) */
                date_from?: string | null;
                /** @description updated_at < día siguiente (YYYY-MM-DD UTC) */
                date_to?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leads_internal_leads_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
                stage?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_internal_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_conversation_panel_internal_conversations__conversation_id__panel_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationPanelPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPanelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_handoff_internal_conversations__conversation_id__handoff_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_settings_internal_settings_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_workspace_settings_internal_settings_put: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_agent_catalog_upload_internal_settings_agent_catalog_parse_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_agent_catalog_upload_internal_settings_agent_catalog_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogParseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    prometheus_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
